require("configs.keymaps")
require("configs.options")
require("configs.plugins.lsp")
require("configs.lazy-loader")
require("configs.theme_config")
require("configs.plugins.colorschemes")
require("configs.plugins.telescope")
require("configs.plugins.leap-nvim")
